app/views.py
from . import db
from .models import Account
from random import randint
from . import qamodel
from . import summarymodel
from . import semsimmodel

from . import geometrymodel
from . import grademodel
from . import profilemodel
from . import geometryvectorizer
from . import gradevectorizer
from . import profilevectorizer

from flask_login import login_required, current_user
from flask import Blueprint, render_template, request, flash, redirect, url_for

from sentence_transformers import util

import json
responses = json.load(open('answers.json'))
responses = responses['answers']
import os

from sklearn.feature_extraction.text import CountVectorizer

from PyPDF2 import PdfReader

vectorizer = CountVectorizer(binary=True)

views = Blueprint('views', __name__, url_defaults=None, root_path=None ) #template_folder not specified

@views.route('/chooseser', methods=['GET','POST'])
@login_required
def chooseser():
    return render_template('chooseser.html')

# Dashboard
@views.route('/queries', methods=['GET', 'POST'])
@login_required
def queries():
    if request.method == 'POST':
        message = request.form.get('message')
        scores = []
        for i in responses:
            scores.append(plagresult(message,i))
            print(i)
        answer = responses[scores.index(max(scores))]
        code = scores.index(max(scores))
        return render_template('queries.html', user=current_user, response=answer, code=code)
    return render_template('queries.html', user=current_user,response='', code='')

# General Services
@views.route('/evaluator', methods=['GET', 'POST'])
@login_required
def evaluator():
    if request.method == 'POST':
        theirpdf = request.files['answer']
        checkpdf = request.files['key']
        if theirpdf and checkpdf:
            theirpdf.save(theirpdf.filename)
            checkpdf.save(checkpdf.filename)
            theirpdfdata = PdfReader(theirpdf.filename)
            checkpdfdata = PdfReader(checkpdf.filename)
            theirpdfdata = ''.join([theirpdfdata.pages[i].extract_text() for i in range(len(theirpdfdata.pages))])
            checkpdfdata = ''.join([checkpdfdata.pages[i].extract_text() for i in range(len(checkpdfdata.pages))])
            os.remove(theirpdf.filename)
            os.remove(checkpdf.filename)
            semscore = plagresult(theirpdfdata,checkpdfdata)
            semscore = round(semscore.item()*100, 2)
            return render_template('evaluator.html', user=current_user, semscore=semscore)
    return render_template('evaluator.html', user=current_user, semscore='')


@views.route('/plagsim', methods=['GET','POST'])
@login_required
def plagsim():
    if request.method == 'POST':
        theirplagtext = request.form.get('theirplagtext')
        checkplagtext = request.form.get('checkplagtext')
        if theirplagtext and checkplagtext:
            simscore = plagresult(theirplagtext,checkplagtext)
            simscore = round(simscore.item()*100, 2)
        else:
            simscore = "Enter Valid Inputs"
        return render_template('plagsim.html', user=current_user, simscore=simscore)
    return render_template('plagsim.html', user=current_user, simscore="")

@views.route('/pdfsim', methods=['GET','POST'])
@login_required
def pdfsim():
    if request.method == 'POST':
        theirpdf = request.files['theirpdf']
        checkpdf = request.files['checkpdf']
        if theirpdf and checkpdf:
            theirpdf.save(theirpdf.filename)
            checkpdf.save(checkpdf.filename)
            theirpdfdata = PdfReader(theirpdf.filename)
            checkpdfdata = PdfReader(checkpdf.filename)
            theirpdfdata = ''.join([theirpdfdata.pages[i].extract_text() for i in range(len(theirpdfdata.pages))])
            checkpdfdata = ''.join([checkpdfdata.pages[i].extract_text() for i in range(len(checkpdfdata.pages))])
            os.remove(theirpdf.filename)
            os.remove(checkpdf.filename)
            simscore = plagresult(theirpdfdata,checkpdfdata)   
            simscore = round(simscore.item()*100, 2)     
        return render_template('pdfsim.html', user=current_user, simscore=simscore)
    return render_template('pdfsim.html', user=current_user, simscore="")

@views.route('/bertsum', methods=['GET','POST'])
@login_required
def bertsum():
    if request.method == 'POST':
        theirsumtext = request.form.get('theirsumtext')
        textsentences = request.form.get('textsentences')
        print(theirsumtext, textsentences)
        if theirsumtext:
            textsummary = summarizer(theirsumtext,sentences=textsentences)
        else:
            textsummary = "Please Enter Valid Input"
        return render_template('bertsum.html', user=current_user,textsummary=textsummary)
    return render_template('bertsum.html',user=current_user,textsummary="")

@views.route('/pdfsum', methods=['GET','POST'])
@login_required
def pdfsum():
    if request.method == 'POST':
        theirpdf = request.files['theirpdf']
        textsentences = request.form.get('textsentences')
        if theirpdf:
            theirpdf.save(theirpdf.filename)
            theirpdfdata = PdfReader(theirpdf.filename)
            theirpdfdata = ''.join([theirpdfdata.pages[i].extract_text() for i in range(len(theirpdfdata.pages))])
            os.remove(theirpdf.filename)
            textsummary = summarizer(theirpdfdata,sentences=textsentences)
        return render_template('pdfsum.html', user=current_user,textsummary=textsummary)
    return render_template('pdfsum.html',user=current_user,textsummary="")

@views.route('/qa', methods=['GET','POST'])
@login_required
def qa():
    if request.method == 'POST':
        theirqatext = request.form.get('theirqatext')
        theirqas = request.form.get('theirqas')
        if theirqatext and theirqas:
            answers = qaanswers(theirqatext, theirqas.split(';'))
            #answers = "".join(i for i in answers)
        else:
            answers = "Inputs are not valid. Please Enter Q's separates by semicolons for your text data"
        return render_template('qa.html',user=current_user, answers=answers)
    return render_template('qa.html',user=current_user,answers="")

@views.route('/pdfqa', methods=['GET','POST'])
@login_required
def pdfqa():
    if request.method == 'POST':
        theirpdf = request.files['theirpdf']
        theirqas = request.form.get('query')
        if theirpdf and theirqas:
            theirpdf.save(theirpdf.filename)
            theirpdfdata = PdfReader(theirpdf.filename)
            theirpdfdata = ''.join([theirpdfdata.pages[i].extract_text() for i in range(len(theirpdfdata.pages))])
            os.remove(theirpdf.filename)
            answers = qaanswers(theirpdfdata, theirqas.split(';'))
            print(answers)
        return render_template('pdfqa.html',user=current_user, answers=answers)
    return render_template('pdfqa.html',user=current_user,answers="")

# Department Services

@views.route('/machining',methods=['GET','POST']) 
@login_required
def machining():
    if request.method == 'POST':
        option = request.form.get('option')
        query = request.form.get('query')
        answer = recommender(query,option)
        return render_template('machining.html',user=current_user, answer=answer, option=option )
    return render_template('machining.html',user=current_user, answer='', option='')

@views.route('/qaentomology', methods=['GET', 'POST'])
@login_required
def qaentomology():
    if request.method == 'POST':
        concept = request.form.get('concept')
        question = request.form.get('query')
        data = json.load(open('entomology.json'))
        concept = data[concept]
        answer = qaanswers(concept, question.split(';'))
        return render_template('qaentomology.html',user=current_user, answer=answer)
    return render_template('qaentomology.html', user=current_user, answer='')

@views.route('/genques', methods=['GET', 'POST'])
@login_required
def genques():
    if request.method == 'POST':
        data = {
            'Remember':['Under which phylum do Insects fall under?','How are insects classified?'],
            'Understand':['What happens when the clitellum of a earthworm is filled with eggs?','What is the function of the clitellum?']
        }
        questions = [data['Remember'][randint(0,1)],data['Understand'][randint(0,1)]]
        return render_template('genques.html', user=current_user, questions=questions)
    return render_template('genques.html', user=current_user, questions='')

#Model Methods     

def qaanswers(theirqatext, theirqas):
    answers = []
    temp = ''
    for i in theirqas:
        temp = qamodel({'context':theirqatext,'question': i})
        answers.append((i,temp['answer'],round(temp['score']*100,2)))
    return answers

def plagresult(text1,text2):
    text1_representation = semsimmodel.encode(text1)
    text2_representation = semsimmodel.encode(text2)
    cosine_sim = util.pytorch_cos_sim(text1_representation,text2_representation)   
    return cosine_sim 

def summarizer(data,sentences=5):
    answer = summarymodel(data, num_sentences=int(sentences), min_length=5)
    return answer

def recommender(text, option):
    if option == 'insertgrade':
        text = gradevectorizer.transform([text])
        return grademodel.predict(text)
    if option == 'insertgeometry':
        text = geometryvectorizer.transform([text])
        return geometrymodel.predict(text)
    if option == 'insertprofile':
        text = profilevectorizer.transform([text])
        return profilemodel.predict(text)

def evaluator(text):
    pass

app/templates/chooseser.html
<!DOCTYPE html>
<html>
    <head>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
          body{
            background-image: url("https://wallpaperaccess.com/full/2825704.gif");
            background-position: center;
            background-origin: content-box;
            background-repeat: no-repeat;
            background-size: cover;
            min-height:100vh;
            font-family: 'Lato', sans-serif;
            align: center;
            color:#ffffff;
          }
          .btn{
            color:#fff;
            background-color:#e74c3c;
            outline: none;
            border: 0;
            color: #fff;
            padding:10px 20px;
            text-transform:uppercase;
            margin-top:50px;
            border-radius:2px;
            cursor:pointer;
            position:relative;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            width:80%;
            font-size:15px;
            text-align:center;
        }
        /*.btn:after{
            content:"";
            position:absolute;
            background:rgba(0,0,0,0.50);
            top:0;
            right:0;
            width:100%;
            height:100%;
            align:center;
        }*/
        .btn:hover{
            background-color:#fff;
            color:#e74c3c;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
        }
        .but{
            color:#fff;
            background-color:#e74c3c;
            outline: none;
            border: 0;
            color: #fff;
            padding:10px 20px;
            text-transform:uppercase;
            margin-top:50px;
            border-radius:2px;
            cursor:pointer;
            position:relative;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            width:80%;
            font-size:15px;
            text-align:center;
        }
        /*.but:after{
            content:"";
            position:absolute;
            background:rgba(0,0,0,0.50);
            top:0;
            right:0;
            width:100%;
            height:100%;
        }*/
        .but:hover{
            background-color:#fff;
            color:#e74c3c;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
        }
        .center{
            text-align: center;
            top:10%;
        }
        .box{
            position:absolute;
            right:50%;
            top: 10%;
            background-color: rgba(0, 0, 0, 0.85);
            border-radius:5px;
            padding:2px 150px;
        }
        .boxe{
            position:absolute;
            left: 55%;
            top: 10%;
            background-color: rgba(0, 0, 0, 0.85);
            border-radius:5px;
            padding:20px 150px;
        }
        .dropdown {
            position: relative;
            display: inline-block;
            padding:10px 40px;
            width:80%;
          }   
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #ffffff;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
        .dropdown-content a {
            color: black;
            padding: 12px 20px;
            text-decoration: none;
            display: block;
          }
          .dropdown-content a:hover {background-color: #ffffff;}
          .dropdown:hover .dropdown-content {display: block;}
          .dropdown:hover .dropbtn {background-color: #ffffff;}
          .dropbtn{
            color:#fff;
            background-color:#e74c3c;
            outline: none;
            border: 0;
            color: #fff;
            padding:10px 20px;
            text-transform:uppercase;
            margin-top:50px;
            border-radius:2px;
            cursor:pointer;
            position:relative;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            width:100%;
            font-size:15px;
            text-align:center;
        }
        /*.dropbtn:after{
            content:"";
            position:absolute;
            background:rgba(0,0,0,0.50);
            top:0;
            right:0;
            width:100%;
            height:100%;
            align:center;
        }*/
        .dropbtn:hover{
            background-color:#fff;
            color:#e74c3c;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
        }
        .dash{
                color:#fff;
                background-color:#e74c3c;
                outline: none;
                border: 0;
                color: #fff;
                padding:10px 20px;
                text-transform:uppercase;
                margin-top:50px;
                border-radius:2px;
                cursor:pointer;
                position:relative;
                top:690px;
                left:1348px;
                -ms-transform: translate(-50%, -50%);
                transform: translate(-50%, -50%);
                width:15%;
                font-size: 12px;
                display: inline-block;
                margin:auto;
            }
            .dash:hover{
                background-color:#fff;
                color:#e74c3c;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
            }
        </style>
        <meta charset="utf-8">
        <title>CTDT Project</title>
    </head>
    <body>
        <h1 style="text-align:center"> CHOOSE YOUR SERVICE </h2>
        <div class="box">
            <h2 class="center"> GENERAL SERVICES </h2>
            <a href='{{ url_for('views.evaluator') }}'style="white-space: nowrap"><!--Link to evaluator.html-->
                <button class="btn">
                    Evaluator
                </button>
            </a>
            <br>
            <a href='{{ url_for('views.machining') }}'style="white-space: nowrap"><!--Link to machining.html-->
                <button class="btn">
                    Machining
                </button>
            </a>
            <div class="dropdown">
                <button class="dropbtn" style="white-space: nowrap">
                    Plagiarism Checker
                </button>
                <div class="dropdown-content">
                    <a href="{{ url_for('views.pdfsim') }}">PDF input based</a><!--Link to pdfsim.html-->
                    <a href="{{ url_for('views.plagsim') }}">Text-input based</a><!--Link to plagsim.html-->
                </div>
            </div>
            <br>
            <div class="dropdown">
                <button class="dropbtn" style="white-space: nowrap">
                    Q&A
                </button>
                <div class="dropdown-content">
                    <a href="{{ url_for('views.pdfqa') }}">PDF input based</a><!--Link to pdfqa.html-->
                    <a href="{{ url_for('views.qa') }}">Text-input based</a><!--Link to qa.html-->
                </div>
            </div>
            <br>
            <a href='{{ url_for('views.genques') }}'style="white-space: nowrap"><!--Link to genques.html-->
                <button class="btn">
                    Question Generator
                </button>
            </a>
            <br>
            <div class="dropdown">
                <button class="dropbtn" style="white-space: nowrap">
                    Extractive Summarizer
                </button>
                <div class="dropdown-content">
                    <a href="{{ url_for('views.pdfsum') }}">PDF input based</a><!--Link to pdfsum.html-->
                    <a href="{{ url_for('views.bertsum') }}">Text-input based</a><!--Link to bertsum.html-->
                </div>
            </div>
        </div>
        <div class="boxe">
            <h2 class="center" style="white-space: nowrap"> DEPARTMENTAL SERVICES </h2>
            <a href="{{ url_for('views.qaentomology') }}" style="white-space: nowrap"><!--Link to qaentomology.html-->
                <button class="but">
                    Entomology
                </button>
            </a>
        </div>
        <a href=></a>
            <button type="dash" class="dash" text-align="center"><!--Link to dashboard.html-->
                <a href="{{ url_for('sign.dashboard') }}">Back</a>
            </button>
        </a>
    </body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html>
    <head>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
          body{
            background-image: url("https://wallpaperaccess.com/full/2825704.gif");
            background-position: center;
            background-origin: content-box;
            background-repeat: no-repeat;
            background-size: cover;
            min-height:100vh;
            font-family: 'Lato', sans-serif;
            align: center;
            color:#ffffff;
          }
          ::selection{
            color: #000;
            background: #fff;
          }
          nav{
            position: absolute;
            left:0%;
            top:0%;
            background: #1b1b1b;
            width: 100%;
            padding: 17px 0;
            z-index: 12;
            display: inline-block;
            animation: slide-in 1s ease-out;
          }

          nav .menu{
            max-width: 1250px;
            margin: auto;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 20px;
          }
          .menu .logo a{
            text-decoration: none;
            color: #fff;
            font-size: 40px;
            font-weight: 600;
          }
          .menu ul{
            display: inline-flex;
          }
          .menu ul li{
            list-style: none;
            margin-left: 7px;
          }
          .menu ul li:first-child{
            margin-left: 0px;
          }
          .menu ul li a{
            text-decoration: none;
            color: #fff;
            font-size: 18px;
            font-weight: 500;
            padding: 8px 15px;
            border-radius: 5px;
            transition: all 0.3s ease;
          }
          .menu ul li a:hover{
            background: #fff;
            color: black;
          }
          .img{
            background: url('img3.jpg')no-repeat;
            width: 100%;
            height: 100vh;
            background-size: cover;
            background-position: center;
            position: relative;
          }
          .img::before{
            content: '';
            position: absolute;
            height: 100%;
            width: 100%;
            background: rgba(0, 0, 0, 0.4);
          }
          .center{
            position: absolute;
            top: 52%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            padding: 0 20px;
            text-align: center;
          }
          .center .title{
            color: #fff;
            font-size: 55px;
            font-weight: 600;
          }
          .center .sub_title{
            color: #fff;
            font-size: 52px;
            font-weight: 600;
          }
          .center .btns{
            margin-top: 20px;
          }
          .center .btns button{
            height: 55px;
            width: 170px;
            border-radius: 5px;
            border: none;
            margin: 0 10px;
            border: 2px solid white;
            font-size: 20px;
            font-weight: 500;
            padding: 0 10px;
            cursor: pointer;
            outline: none;
            transition: all 0.3s ease;
          }
          .center .btns button:first-child{
            color: #fff;
            background: none;
          }
          .btns button:first-child:hover{
            background: white;
            color: black;
          }
          .center .btns button:last-child{
            background: white;
            color: black;
          }
        </style>
        <meta charset="utf-8">
        <title>CTDT Project</title>
    </head>
    <body>
        <nav>
            <div class="menu">
              <div class="logo">
                <a href="#">AltGPT</a>
              </div>
              <ul>
                <li><a href="{{ url_for('sign.login')}}">SIGN IN</a></li><!--Link to login.html-->
                <li><a href="{{ url_for('sign.create_account')}}">REGISTER</a></li><!--Link to create_account.html-->
              </ul>
            </div>
        </nav>
        <div class="img"></div>
            <div class="center">
                <div class="title">Welcome to AltGPT</div>
                <div class="sub_title">Your No.1 Pedagogical Chatbot</div>
                <div class="btns">
                <button><a href="{{ url_for('sign.aboutalt')}}">Learn More</a></button> <!--Link to aboutalt.html-->
                <button><a href="{{ url_for('views.queries') }}">Queries?</a></button> <!--Link to queries.html-->
            </div>
        </div>
    </body>
</html>

app/templates/queries.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
            body {
                font-family: "Lato", sans-serif;
                padding-bottom: 100px;
                margin: 0;
                background-image: url("https://media.giphy.com/media/BHNfhgU63qrks/giphy.gif");
                background-position: center;
                background-origin: content-box;
                background-repeat: no-repeat;
                background-size: cover;
                min-height:100vh;
                font-family: 'Lato', sans-serif;
                align: center;
                color:#ffffff;
            }
            .box{
                position:absolute;
                left:50%;
                top: 67%;
                transform: translate(-50%,-50%);
                background-color: rgba(0, 0, 0, 0.85);
                border-radius:5px;
                padding:22px 150px;
            }
            .input-container{
                position:relative;
                margin:50px;
                align-items: center;
                right:5px;
            }
            .input-container label{
                position:absolute;
                top:-35px;
                left:10px;
                color:#fff;	
                pointer-event:none;
                font-size:16px;
                top: 0;
                left: 50%;
                transform: translate(-50%, -50%);
                white-space: nowrap;
                text-align:center;
            }
            .input-container input{ 
                border:0.5px solid #555;
                border-width:3px; 
                border-style:solid; 
                border-radius:3px;            
                background:transparent;
                width:100%;
                padding:8px 0 5px 0;
                font-size:16px;
                color:#fff;
            }
            .input-container input:focus{ 
                border:1px solid #FE7984;
                outline:none;	
            }
            .btn{
                color:#fff;
                background-color:#FE7984;
                outline: none;
                border: 0;
                color: #fff;
                padding:10px 20px;
                text-transform:uppercase;
                margin-top:50px;
                border-radius:2px;
                cursor:pointer;
                position:relative;
                top: 50%;
                left: 50%;
                -ms-transform: translate(-50%, -50%);
                transform: translate(-50%, -50%);
                width:40%;
                font-size:15px;
            }
            /*.btn:after{
                content:"";
                position:absolute;
                background:rgba(0,0,0,0.50);
                top:0;
                right:0;
                width:100%;
                height:100%;
                align:center;
            }*/
            .btn:hover{
                background-color:#fff;
                color:#FE7984;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
            }
            textarea{
                margin-top: 10px;
                -moz-border-bottom-colors: none;
                -moz-border-left-colors: none;
                -moz-border-right-colors: none;
                -moz-border-top-colors: none;
                background: none repeat scroll rgba(0, 0, 0, 0.35);
                border-color: -moz-use-text-color #555;
                border-image: none;
                border-radius: 3px;
                border-style: none solid solid none;
                border-width: medium 1px 1px medium;
                box-shadow: 0 1px 2px rgba(234, 109, 47, 0.948) inset;
                color: #fff;
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 1em;
                line-height: 1.4em;
                padding: 5px 8px;
                transition: background-color 0.2s ease 0s;
                outline: #e74c3c;
                resize: none;
                overflow: none;
                border:1px solid #ffffff;
                vertical-align: top;
            }
            textarea:focus {
                background: none repeat scroll 0 0 #1d1d1d2c;
                outline-width: 0;
                border:1px solid #FE7984;
                outline:none;
            }
            .dash{
                color:#fff;
                background-color:#B44578;
                outline: none;
                border: 0;
                color: #fff;
                padding:10px 20px;
                text-transform:uppercase;
                margin-top:50px;
                border-radius:2px;
                cursor:pointer;
                position:relative;
                top:675px;
                left:1330px;
                -ms-transform: translate(-50%, -50%);
                transform: translate(-50%, -50%);
                width:15%;
                font-size: 12px;
                display: inline-block;
                margin:auto;
            }
            .dash:hover{
                background-color:#fff;
                color:#B44578;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
            }
            .center{
                text-align: center;
                font-size:60px;
                top:10%;
            }
        </style>
        <title>CHATBOT</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h2 class="center"> CHATBOT </h2>
        <div class="box">
            <form action="" method="POST">
                <div id="body" class="input-container" style="width:400px;">
                    <br>
                    <textarea name="message" rows="1" cols="46" id="message" required="" wrap="off" autocomplete="off" aria-autocomplete="list" aria-haspopup="true"></textarea>
                    <br>
                    <label for="message"><h3 style="font-size:18px;text-align:center">Drop your message here</h3></label> 
                </div>
                <div id="body" class="input-container" style="width:400px;">
                    <p></p><button type="submit" class="btn" text-align="center">Submit</button>
                </div>
            </form>
            <h2 style="text-align:center"> ALTGPT Response </h2>
            <p>Here is the response</p>
            <p> {{ response }} </p>
            {% if code == 4 %}
                <a href="{{ url_for('views.pdfsum') }}">File Summarizer</a>
            {% elif code == 5 %}
                <a href="{{ url_for('views.bertsum') }}">Text Summarizer</a>
            {% elif code == 7 %}
                <a href="{{ url_for('views.plagsim') }}">Text Similarity</a>
            {% elif code == 6 %}
                <a href="{{ url_for('views.pdfsim') }}">File Similarity</a>
            {% elif code == 9 %}
            <a href="{{ url_for('views.qa') }}">Text Q&A</a>
            {% elif code == 8 %}
                <a href="{{ url_for('views.pdfqa') }}">File Q&A</a>
            {% elif code == 10 %}
                <a href="{{ url_for('views.qaentomology') }}">Entomology</a>
            {% elif code == 13 %}
                <a href="{{ url_for('views.machining') }}">Machining</a>
            {% else %}
                <p></p>
            {% endif %}
        </div> 
        <a href=></a>
            <button type="dash" class="dash" text-align="center"><!--Link to dashboard.html-->
                <h4>Back</h4>
            </button>
        </a>
    </body>
</html>